#!/usr/bin/env python
# -*- coding: utf-8 -*-

print('turtle')
print('turtle')
print('turtle')
print('turtle')
print('turtle')
print('turtle')
print('turtle')
print('turtle')
print('turtle')
print('turtle')
print('turtle')
print('turtle')
print('turtle')
print('turtle')
print('turtle')
print('turtle')
print('turtle')
print('turtle')
print('turtle')
print('turtle')
